import { ClipboardList, ShieldAlert, UserRound } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { getListClaimsQueryKey, useCreateClaim, useListClaims } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { AppShell, QuickAdd } from '@/components/app-shell';
import { EmptyState, ErrorState, Field, FilterSelect, LoadingRows, Modal, PageHeader, Panel, SearchBox, shortDate, StatusPill, ToastMessage } from '@/components/ui-kit';

export default function Claims() {
  const queryClient = useQueryClient(); const list = useListClaims({ query: { queryKey: getListClaimsQueryKey() } }); const create = useCreateClaim();
  const [open, setOpen] = useState(false); const [selected, setSelected] = useState<string | null>(null); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('All statuses'); const [toast, setToast] = useState('');
  const [form, setForm] = useState({ policyNumber: '', customerName: '', incident: '', amount: '' });
  const claims = useMemo(() => (list.data ?? []).filter((c) => `${c.claimNumber} ${c.policyNumber} ${c.customerName} ${c.incident}`.toLowerCase().includes(search.toLowerCase())).filter((c) => filter === 'All statuses' || c.status === filter), [list.data, search, filter]);
  const current = claims.find((c) => c.id === selected); const set = (key: keyof typeof form) => (value: string) => setForm((old) => ({ ...old, [key]: value }));
  const submit = (e: FormEvent) => { e.preventDefault(); create.mutate({ data: { ...form, amount: Number(form.amount) } }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListClaimsQueryKey() }); setOpen(false); setForm({ policyNumber: '', customerName: '', incident: '', amount: '' }); setToast('Claim registered with the desk'); }, onError: () => setToast('Could not register claim. Try again.') }); };
  return <AppShell><div className="page-enter"><PageHeader eyebrow="Service & resolution" title="Claims queue" description="Make the next step visible. Prioritise the cases that need a human hand today." action={<QuickAdd label="Register claim" onClick={() => setOpen(true)} />} />
    <div className="mb-4 flex flex-col gap-2 sm:flex-row"><SearchBox value={search} onChange={setSearch} placeholder="Search claim or policy" /><FilterSelect value={filter} onChange={setFilter} options={['All statuses', 'Open', 'Under review', 'Approved', 'Settled']} /></div>
    <Panel>{list.isError ? <ErrorState onRetry={() => list.refetch()} /> : list.isLoading ? <LoadingRows /> : claims.length === 0 ? <EmptyState title="No claims in this queue" description="Newly registered claims will land here with a clear owner and priority." action={<button onClick={() => setOpen(true)} className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground" data-testid="button-empty-register-claim">Register a claim</button>} /> : <div className="overflow-x-auto"><div className="min-w-[960px]"><div className="grid grid-cols-[1fr_1.1fr_1.4fr_.8fr_.8fr_.8fr_1fr] gap-4 border-b border-border bg-muted/35 px-5 py-3 mono text-[9px] uppercase tracking-[.16em] text-muted-foreground"><span>Claim</span><span>Policy</span><span>Customer / incident</span><span>Reported</span><span>Amount</span><span>Priority</span><span>Status</span></div>{claims.map((c) => <button key={c.id} onClick={() => setSelected(c.id)} data-testid={`row-claim-${c.id}`} className="grid w-full grid-cols-[1fr_1.1fr_1.4fr_.8fr_.8fr_.8fr_1fr] items-center gap-4 border-b border-border/70 px-5 py-4 text-left transition-colors last:border-0 hover:bg-muted/25"><div><div className="mono text-xs font-medium text-primary">{c.claimNumber}</div><div className="mt-1 text-[10px] text-muted-foreground">{c.assignee}</div></div><div className="mono text-[11px]">{c.policyNumber}</div><div><div className="text-xs font-extrabold">{c.customerName}</div><div className="mt-0.5 max-w-[180px] truncate text-[10px] text-muted-foreground">{c.incident}</div></div><div className="text-[11px] text-muted-foreground">{shortDate(c.reportedAt)}</div><div className="mono text-xs">{c.amount ? `₹${c.amount.toLocaleString('en-IN')}` : '—'}</div><span className={`w-fit rounded-full px-2 py-1 text-[10px] font-bold capitalize ${c.priority === 'High' ? 'bg-[#fce4e1] text-[#a93b32]' : 'bg-[#fff0d6] text-[#95601c]'}`}>{c.priority}</span><StatusPill value={c.status} /></button>)}</div></div>}</Panel>
    {current && <Modal title={current.claimNumber} description={`${current.customerName} · ${current.policyNumber}`} onClose={() => setSelected(null)}><div className="p-5"><div className="flex items-start gap-3 rounded-xl bg-[#fff0d6] p-4 text-[#80511c]"><ShieldAlert size={19} /><div><div className="text-xs font-extrabold">Next step required</div><div className="mt-1 text-[11px] leading-5">Review the incident evidence and keep the customer updated before the SLA checkpoint.</div></div></div><div className="mt-4 space-y-3"><div className="flex gap-3"><ClipboardList size={15} className="mt-0.5 text-primary" /><div><div className="mono text-[9px] uppercase tracking-wider text-muted-foreground">Incident</div><div className="mt-1 text-xs font-semibold">{current.incident}</div></div></div><div className="flex gap-3"><UserRound size={15} className="mt-0.5 text-primary" /><div><div className="mono text-[9px] uppercase tracking-wider text-muted-foreground">Assigned to</div><div className="mt-1 text-xs font-semibold">{current.assignee}</div></div></div></div><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><StatusPill value={current.status} /><button onClick={() => setToast('Claim note saved for the service team')} data-testid="button-add-claim-note" className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground">Add desk note</button></div></div></Modal>}
    {open && <Modal title="Register a claim" description="Give the service team the context they need from the first handoff." onClose={() => setOpen(false)}><form onSubmit={submit} className="space-y-4 p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Policy number" name="claim-policy-number" value={form.policyNumber} onChange={set('policyNumber')} placeholder="POL/2024/00814" /><Field label="Customer" name="claim-customer" value={form.customerName} onChange={set('customerName')} placeholder="Customer name" /></div><Field label="What happened?" name="claim-incident" value={form.incident} onChange={set('incident')} placeholder="Short description of the incident" /><Field label="Estimated amount" name="claim-amount" type="number" value={form.amount} onChange={set('amount')} placeholder="150000" /><div className="flex justify-end gap-2 border-t border-border pt-4"><button type="button" onClick={() => setOpen(false)} className="rounded-lg px-3 py-2 text-xs font-bold text-muted-foreground hover:bg-muted" data-testid="button-cancel-claim">Cancel</button><button disabled={create.isPending} type="submit" className="rounded-lg bg-primary px-4 py-2 text-xs font-bold text-primary-foreground disabled:opacity-60" data-testid="button-submit-claim">{create.isPending ? 'Registering…' : 'Register claim'}</button></div></form></Modal>}{toast && <ToastMessage message={toast} onDismiss={() => setToast('')} />}</div></AppShell>;
}