import { MapPin, Plus } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { useListCustomers, useCreateCustomer, getListCustomersQueryKey } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { AppShell, QuickAdd } from '@/components/app-shell';
import { EmptyState, ErrorState, Field, FilterSelect, initials, LoadingRows, Modal, PageHeader, Panel, SearchBox, StatusPill, ToastMessage } from '@/components/ui-kit';

export default function Customers() {
  const queryClient = useQueryClient(); const list = useListCustomers({ query: { queryKey: getListCustomersQueryKey() } }); const create = useCreateCustomer();
  const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('All types'); const [toast, setToast] = useState('');
  const [form, setForm] = useState({ name: '', businessName: '', type: 'Private limited', location: '' });
  const customers = (list.data ?? []).filter((c) => `${c.name} ${c.businessName} ${c.location}`.toLowerCase().includes(search.toLowerCase())).filter((c) => filter === 'All types' || c.type === filter);
  const set = (key: keyof typeof form) => (value: string) => setForm((old) => ({ ...old, [key]: value }));
  const submit = (e: FormEvent) => { e.preventDefault(); create.mutate({ data: form }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListCustomersQueryKey() }); setOpen(false); setForm({ name: '', businessName: '', type: 'Private limited', location: '' }); setToast('Customer added to your book'); }, onError: () => setToast('Could not add customer. Try again.') }); };
  return <AppShell><div className="page-enter"><PageHeader eyebrow="Relationship book" title="Customers" description="One clear view of the businesses you protect, their policies, and what needs attention next." action={<QuickAdd label="Add customer" onClick={() => setOpen(true)} />} />
    <div className="mb-4 flex flex-col gap-2 sm:flex-row"><SearchBox value={search} onChange={setSearch} placeholder="Search by name or business" /><FilterSelect value={filter} onChange={setFilter} options={['All types', 'Private limited', 'Partnership', 'Sole proprietorship', 'LLP']} /></div>
    <Panel>{list.isError ? <ErrorState onRetry={() => list.refetch()} /> : list.isLoading ? <LoadingRows /> : customers.length === 0 ? <EmptyState title={search ? 'No customers match that search' : 'Your customer book is ready'} description={search ? 'Try a wider search or clear the filters.' : 'Add your first customer to start building a connected operations record.'} action={<button onClick={() => setOpen(true)} className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground" data-testid="button-empty-add-customer"><Plus size={13} className="mr-1 inline" />Add customer</button>} /> : <div className="overflow-x-auto"><div className="min-w-[720px]"><div className="grid grid-cols-[1.5fr_1.2fr_1fr_.6fr_.7fr_24px] gap-4 border-b border-border bg-muted/35 px-5 py-3 mono text-[9px] uppercase tracking-[.16em] text-muted-foreground"><span>Customer</span><span>Business</span><span>Location</span><span>Policies</span><span>Status</span><span /></div>{customers.map((c) => <div key={c.id} data-testid={`row-customer-${c.id}`} className="grid grid-cols-[1.5fr_1.2fr_1fr_.6fr_.7fr_24px] items-center gap-4 border-b border-border/70 px-5 py-4 transition-colors last:border-0 hover:bg-muted/25"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-secondary text-[11px] font-extrabold text-primary">{initials(c.name)}</div><div><div className="text-xs font-extrabold">{c.name}</div><div className="mt-0.5 text-[10px] text-muted-foreground">{c.type}</div></div></div><div className="text-xs font-semibold">{c.businessName}</div><div className="flex items-center gap-1.5 text-xs text-muted-foreground"><MapPin size={13} />{c.location}</div><div className="mono text-xs font-medium">{c.policies}</div><StatusPill value={c.status} /><span className="text-muted-foreground">›</span></div>)}</div></div>}</Panel>
    {open && <Modal title="Add a customer" description="Create a relationship record before you start a quote." onClose={() => setOpen(false)}><form onSubmit={submit} className="space-y-4 p-5"><Field label="Primary contact" name="name" value={form.name} onChange={set('name')} placeholder="e.g. Rohan Mehta" /><Field label="Business name" name="business-name" value={form.businessName} onChange={set('businessName')} placeholder="e.g. Mehta Auto Components" /><div><label className="mb-1.5 block text-[11px] font-bold">Business type<span className="ml-0.5 text-destructive">*</span></label><select value={form.type} onChange={(e) => set('type')(e.target.value)} data-testid="select-business-type" className="h-10 w-full rounded-lg border border-input bg-background px-3 text-xs outline-none focus:border-primary"><option>Private limited</option><option>Partnership</option><option>Sole proprietorship</option><option>LLP</option></select></div><Field label="City" name="location" value={form.location} onChange={set('location')} placeholder="e.g. Pune, Maharashtra" /><div className="flex justify-end gap-2 border-t border-border pt-4"><button type="button" onClick={() => setOpen(false)} className="rounded-lg px-3 py-2 text-xs font-bold text-muted-foreground hover:bg-muted" data-testid="button-cancel-customer">Cancel</button><button disabled={create.isPending} type="submit" className="rounded-lg bg-primary px-4 py-2 text-xs font-bold text-primary-foreground disabled:opacity-60" data-testid="button-submit-customer">{create.isPending ? 'Saving…' : 'Save customer'}</button></div></form></Modal>}{toast && <ToastMessage message={toast} onDismiss={() => setToast('')} />}</div></AppShell>;
}