import { CalendarClock, Download, ShieldCheck } from 'lucide-react';
import { useMemo, useState } from 'react';
import { getListPoliciesQueryKey, useListPolicies } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';
import { compactMoney, EmptyState, ErrorState, FilterSelect, LoadingRows, Modal, PageHeader, Panel, SearchBox, shortDate, StatusPill } from '@/components/ui-kit';

export default function Policies() {
  const list = useListPolicies({ query: { queryKey: getListPoliciesQueryKey() } }); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('All statuses'); const [selected, setSelected] = useState<string | null>(null);
  const policies = useMemo(() => (list.data ?? []).filter((p) => `${p.policyNumber} ${p.customerName} ${p.businessName} ${p.product} ${p.insurer}`.toLowerCase().includes(search.toLowerCase())).filter((p) => filter === 'All statuses' || p.status === filter), [list.data, search, filter]);
  const current = policies.find((p) => p.id === selected);
  return <AppShell><div className="page-enter"><PageHeader eyebrow="Book of business" title="Policies" description="Every active cover, expiry date, and risk profile in one dependable register." action={<button onClick={() => window.print()} data-testid="button-export-policies" className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-3.5 py-2.5 text-xs font-bold hover:bg-muted"><Download size={15} />Export register</button>} />
    <div className="mb-4 flex flex-col gap-2 sm:flex-row"><SearchBox value={search} onChange={setSearch} placeholder="Search policy number or customer" /><FilterSelect value={filter} onChange={setFilter} options={['All statuses', 'Active', 'Renewal due', 'Expired']} /></div>
    <Panel>{list.isError ? <ErrorState onRetry={() => list.refetch()} /> : list.isLoading ? <LoadingRows /> : policies.length === 0 ? <EmptyState title="No policies found" description="Issued policies will appear here once a proposal has been converted." /> : <div className="overflow-x-auto"><div className="min-w-[1000px]"><div className="grid grid-cols-[1.15fr_1.35fr_1fr_1fr_.8fr_.85fr_.8fr] gap-4 border-b border-border bg-muted/35 px-5 py-3 mono text-[9px] uppercase tracking-[.16em] text-muted-foreground"><span>Policy</span><span>Customer</span><span>Product</span><span>Insurer</span><span>Premium</span><span>Expiry</span><span>Status</span></div>{policies.map((p) => <button key={p.id} onClick={() => setSelected(p.id)} data-testid={`row-policy-${p.id}`} className="grid w-full grid-cols-[1.15fr_1.35fr_1fr_1fr_.8fr_.85fr_.8fr] items-center gap-4 border-b border-border/70 px-5 py-4 text-left transition-colors last:border-0 hover:bg-muted/25"><div><div className="mono text-xs font-medium text-primary">{p.policyNumber}</div><div className="mt-1 text-[10px] text-muted-foreground">{p.riskType} risk</div></div><div><div className="text-xs font-extrabold">{p.customerName}</div><div className="mt-0.5 text-[10px] text-muted-foreground">{p.businessName}</div></div><div className="text-xs font-semibold">{p.product}</div><div className="text-xs text-muted-foreground">{p.insurer}</div><div className="mono text-xs">{compactMoney(p.premium)}</div><div className="flex items-center gap-1.5 text-[11px] text-muted-foreground"><CalendarClock size={12} />{shortDate(p.expiryDate)}</div><StatusPill value={p.status} /></button>)}</div></div>}</Panel>
    {current && <Modal title={current.policyNumber} description={`${current.customerName} · ${current.businessName}`} onClose={() => setSelected(null)}><div className="p-5"><div className="flex items-center gap-3 rounded-xl bg-secondary/70 p-4"><div className="grid size-10 place-items-center rounded-lg bg-card text-primary"><ShieldCheck size={20} /></div><div><div className="text-sm font-extrabold">{current.product}</div><div className="mt-1 text-[11px] text-muted-foreground">{current.insurer} · {current.riskType} risk</div></div><div className="ml-auto"><StatusPill value={current.status} /></div></div><div className="mt-4 grid grid-cols-2 gap-3">{[['Annual premium', compactMoney(current.premium)], ['Sum insured', compactMoney(current.coverage)], ['Policy expiry', shortDate(current.expiryDate)], ['Policyholder', current.customerName]].map(([label, value]) => <div className="rounded-lg border border-border p-3" key={label}><div className="mono text-[9px] uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-1 text-xs font-extrabold">{value}</div></div>)}</div><div className="mt-5 flex justify-end"><button onClick={() => window.print()} data-testid="button-print-policy" className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-bold hover:bg-muted"><Download size={13} />Print policy summary</button></div></div></Modal>}</div></AppShell>;
}