import { Send } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { useCreateProposal, useCreateQuote, useGetQuote, useListQuotes, getGetQuoteQueryKey, getListQuotesQueryKey } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { AppShell, QuickAdd } from '@/components/app-shell';
import { compactMoney, EmptyState, ErrorState, Field, FilterSelect, LoadingRows, Modal, PageHeader, Panel, SearchBox, shortDate, StatusPill, ToastMessage } from '@/components/ui-kit';

export default function Quotes() {
  const queryClient = useQueryClient(); const list = useListQuotes({ query: { queryKey: getListQuotesQueryKey() } }); const create = useCreateQuote(); const proposal = useCreateProposal();
  const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('All statuses'); const [selected, setSelected] = useState(''); const [toast, setToast] = useState('');
  const [form, setForm] = useState({ customerName: '', businessName: '', location: '', product: 'SME Package', coverage: '2500000' });
  const detail = useGetQuote(selected || '', { query: { enabled: Boolean(selected), queryKey: getGetQuoteQueryKey(selected || '') } });
  const quotes = useMemo(() => (list.data ?? []).filter((q) => `${q.customerName} ${q.businessName} ${q.product} ${q.insurer}`.toLowerCase().includes(search.toLowerCase())).filter((q) => filter === 'All statuses' || q.status === filter), [list.data, search, filter]);
  const set = (key: keyof typeof form) => (value: string) => setForm((old) => ({ ...old, [key]: value }));
  const submit = (e: FormEvent) => { e.preventDefault(); create.mutate({ data: { ...form, coverage: Number(form.coverage) } }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListQuotesQueryKey() }); setOpen(false); setToast('Quote created and ready for review'); setForm({ customerName: '', businessName: '', location: '', product: 'SME Package', coverage: '2500000' }); }, onError: () => setToast('Could not create the quote. Try again.') }); };
  const sendProposal = (quoteId: string, customerName: string) => proposal.mutate({ data: { quoteId, customerName } }, { onSuccess: () => setToast('Proposal sent to the customer'), onError: () => setToast('Proposal could not be sent') });
  return <AppShell><div className="page-enter"><PageHeader eyebrow="Commercial pipeline" title="Quotes" description="Keep every opportunity moving with a clear view of coverage, insurer, and the next handoff." action={<QuickAdd label="New quote" onClick={() => setOpen(true)} />} />
    <div className="mb-4 flex flex-col gap-2 sm:flex-row"><SearchBox value={search} onChange={setSearch} placeholder="Search quotes" /><FilterSelect value={filter} onChange={setFilter} options={['All statuses', 'Draft', 'Quoted', 'Proposal sent', 'Won', 'Expired']} /></div>
    <Panel>{list.isError ? <ErrorState onRetry={() => list.refetch()} /> : list.isLoading ? <LoadingRows /> : quotes.length === 0 ? <EmptyState title="No quotes in this view" description="Start with a customer and shape the right cover for their business." action={<button onClick={() => setOpen(true)} className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground" data-testid="button-empty-add-quote">Create quote</button>} /> : <div className="overflow-x-auto"><div className="min-w-[900px]"><div className="grid grid-cols-[1.3fr_1.1fr_1fr_.8fr_.8fr_.8fr_1fr] gap-4 border-b border-border bg-muted/35 px-5 py-3 mono text-[9px] uppercase tracking-[.16em] text-muted-foreground"><span>Customer</span><span>Product</span><span>Insurer</span><span>Premium</span><span>Coverage</span><span>Expires</span><span>Status</span></div>{quotes.map((q) => <button key={q.id} onClick={() => setSelected(q.id)} data-testid={`row-quote-${q.id}`} className="grid w-full grid-cols-[1.3fr_1.1fr_1fr_.8fr_.8fr_.8fr_1fr] items-center gap-4 border-b border-border/70 px-5 py-4 text-left transition-colors last:border-0 hover:bg-muted/25"><div><div className="text-xs font-extrabold">{q.customerName}</div><div className="mt-0.5 text-[10px] text-muted-foreground">{q.businessName}</div></div><div className="text-xs font-semibold">{q.product}</div><div className="text-xs text-muted-foreground">{q.insurer}</div><div className="mono text-xs">{compactMoney(q.premium)}</div><div className="mono text-xs">{compactMoney(q.coverage)}</div><div className="text-[11px] text-muted-foreground">{shortDate(q.expiresAt)}</div><StatusPill value={q.status} /></button>)}</div></div>}</Panel>
    {selected && <Modal title={detail.data?.businessName ?? 'Quote details'} description={detail.data ? `${detail.data.product} · ${detail.data.insurer}` : 'Loading quote details…'} onClose={() => setSelected('')}><div className="p-5">{detail.isLoading ? <LoadingRows count={2} /> : detail.data ? <><div className="grid grid-cols-2 gap-3">{[['Premium', compactMoney(detail.data.premium)], ['Coverage', compactMoney(detail.data.coverage)], ['Created', shortDate(detail.data.createdAt)], ['Expires', shortDate(detail.data.expiresAt)]].map(([label, value]) => <div key={label} className="rounded-lg bg-muted/50 p-3"><div className="mono text-[9px] uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-1 text-sm font-extrabold">{value}</div></div>)}</div><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><StatusPill value={detail.data.status} /><button onClick={() => sendProposal(detail.data!.id, detail.data!.customerName)} disabled={proposal.isPending} className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground disabled:opacity-60" data-testid="button-send-proposal"><Send size={13} />{proposal.isPending ? 'Sending…' : 'Send proposal'}</button></div></> : <div className="text-sm text-muted-foreground">This quote is unavailable.</div>}</div></Modal>}
    {open && <Modal title="Create a quote" description="Shape an initial cover recommendation for a customer." onClose={() => setOpen(false)}><form onSubmit={submit} className="grid gap-4 p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Customer" name="quote-customer" value={form.customerName} onChange={set('customerName')} placeholder="Contact name" /><Field label="Business" name="quote-business" value={form.businessName} onChange={set('businessName')} placeholder="Business name" /></div><Field label="Location" name="quote-location" value={form.location} onChange={set('location')} placeholder="City, state" /><div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-1.5 block text-[11px] font-bold">Product</label><select value={form.product} onChange={(e) => set('product')(e.target.value)} data-testid="select-quote-product" className="h-10 w-full rounded-lg border border-input bg-background px-3 text-xs"><option>SME Package</option><option>Commercial Property</option><option>Workmen Compensation</option><option>Cyber Liability</option></select></div><Field label="Coverage amount" name="quote-coverage" type="number" value={form.coverage} onChange={set('coverage')} placeholder="2500000" /></div><div className="flex justify-end gap-2 border-t border-border pt-4"><button type="button" onClick={() => setOpen(false)} className="rounded-lg px-3 py-2 text-xs font-bold text-muted-foreground hover:bg-muted" data-testid="button-cancel-quote">Cancel</button><button disabled={create.isPending} type="submit" className="rounded-lg bg-primary px-4 py-2 text-xs font-bold text-primary-foreground disabled:opacity-60" data-testid="button-submit-quote">{create.isPending ? 'Creating…' : 'Create quote'}</button></div></form></Modal>}{toast && <ToastMessage message={toast} onDismiss={() => setToast('')} />}</div></AppShell>;
}